/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qis;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows 10
 */
public class Frm_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Log
     */
    public Frm_Menu() {
        this.setUndecorated(true);
        this.setBackground(new Color(0,0,0,0));
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        this.getContentPane().setBackground(new Color(0,0,0,0));
        this.setLocationRelativeTo(null);
        kGradientPanel1.setOpaque(false);
        
        Authentication auth = new Authentication();
        user = auth.getAuth();
        setUser();
    }
    
    String user = "";

    public void setUser()
    {
        if(user.equals("Cashier"))
        {
            lblLab.setEnabled(false);
            lblImaging.setEnabled(false);
            lblQC.setEnabled(false);
            lblPE.setEnabled(false);
            lblNurse.setEnabled(false);
        }
    }
    
    DefaultTableModel table = new DefaultTableModel()
    {
        public boolean isCellEditable(int row, int column)
        {
            return false;
        }
    };
    
    private void addColumns()
    {
        table.addColumn("Transaction ID");
        table.addColumn("Patient Name");
        table.addColumn("Items");
        table.addColumn("Transaction Date");
    }
    
    private void setTable(ResultSet result)
    {
        try
        {
            int rows=table.getRowCount();
            int z=0;
            
            while(result.next())
            {
                if (!result.getString("ItemID").equals(""))
                {
                    String[] itemID = result.getString("ItemID").split(",");
                    String items = "";
                    z=0;
                    while(z<itemID.length)
                    {
                        Connection con = DatabaseConnect.con;
                        PreparedStatement command = con.prepareStatement("select * from qpd_items where itemID = " + Integer.parseInt(itemID[z]));
                        ResultSet result2 = command.executeQuery(); 
                        while(result2.next())
                        {
                            items += result2.getString("ItemName")+"//";
                        }
                        z++;
                    }

                    items = items.replace("//", ", ");
                    items = items.trim();
                    if(items.charAt(items.length()-1) == ',')
                    {
                        items = items.substring(0, items.length()-1);
                    }

                    table.addRow(new Object[]{
                        result.getString("TransactionID"),
                        result.getString("lastname") + ", " + result.getString("firstname") + " " + result.getString("middlename"),
                        items,
                        result.getString("TransactionDate"),
                    }); 
                }
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        lblCashier = new keeptoo.KButton();
        lblLab = new keeptoo.KButton();
        lblImaging = new keeptoo.KButton();
        lblQC = new keeptoo.KButton();
        lblPE = new keeptoo.KButton();
        lblNurse = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0,0,0,0));

        kGradientPanel1.setkBorderRadius(50);
        kGradientPanel1.setkEndColor(new java.awt.Color(24, 47, 89));
        kGradientPanel1.setkStartColor(new java.awt.Color(45, 210, 228));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(780, 572));

        lblCashier.setText("CASHIER");
        lblCashier.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCashier.setkBorderRadius(30);
        lblCashier.setkEndColor(new java.awt.Color(102, 204, 255));
        lblCashier.setkStartColor(new java.awt.Color(0, 102, 255));
        lblCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCashierActionPerformed(evt);
            }
        });

        lblLab.setText("LABORATORY");
        lblLab.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLab.setkBorderRadius(30);
        lblLab.setkEndColor(new java.awt.Color(255, 204, 204));
        lblLab.setkStartColor(new java.awt.Color(255, 102, 102));
        lblLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLabActionPerformed(evt);
            }
        });

        lblImaging.setText("IMAGING");
        lblImaging.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblImaging.setkBorderRadius(30);
        lblImaging.setkEndColor(new java.awt.Color(204, 255, 204));
        lblImaging.setkStartColor(new java.awt.Color(0, 153, 102));
        lblImaging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblImagingActionPerformed(evt);
            }
        });

        lblQC.setText("QC");
        lblQC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQC.setkBorderRadius(30);
        lblQC.setkEndColor(new java.awt.Color(204, 204, 255));
        lblQC.setkStartColor(new java.awt.Color(102, 0, 153));
        lblQC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblQCActionPerformed(evt);
            }
        });

        lblPE.setText("PE");
        lblPE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPE.setkBorderRadius(30);
        lblPE.setkEndColor(new java.awt.Color(255, 255, 204));
        lblPE.setkStartColor(new java.awt.Color(235, 169, 31));
        lblPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblPEActionPerformed(evt);
            }
        });

        lblNurse.setText("NURSE");
        lblNurse.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNurse.setkBorderRadius(30);
        lblNurse.setkEndColor(new java.awt.Color(0, 255, 204));
        lblNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNurseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblQC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(lblPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(lblNurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblCashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(lblLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(lblImaging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLab, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImaging, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQC, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPE, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNurse, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCashierActionPerformed
        Cashier_Transact main = new Cashier_Transact();
        main.setVisible(true);
        main.toFront();
        this.dispose();
    }//GEN-LAST:event_lblCashierActionPerformed

    private void lblLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLabActionPerformed

    private void lblImagingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblImagingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImagingActionPerformed

    private void lblQCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblQCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQCActionPerformed

    private void lblPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPEActionPerformed

    private void lblNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNurseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNurseActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        Frm_Log main = new Frm_Log();
        main.setVisible(true);
        main.toFront();
        this.dispose();
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        DatabaseConnect.connect();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KButton lblCashier;
    private keeptoo.KButton lblImaging;
    private keeptoo.KButton lblLab;
    private keeptoo.KButton lblNurse;
    private keeptoo.KButton lblPE;
    private keeptoo.KButton lblQC;
    // End of variables declaration//GEN-END:variables
}
